// Reads .env (or environment variables), generates web/config.js and copies shared/ into web/shared/,
// so that web/ is the only folder to deploy.
// Usage: node build.mjs
import { existsSync, readFileSync, writeFileSync, readdirSync, mkdirSync, rmSync, copyFileSync } from 'node:fs';

const root = new URL('.', import.meta.url);
const web = new URL('web/', root);
const envFile = new URL('.env', root);

const fileEnv = {};
if (existsSync(envFile)) {
  for (const line of readFileSync(envFile, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Za-z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (!m || line.trim().startsWith('#')) continue;
    let v = m[2];
    if (/^(["']).*\1$/.test(v)) v = v.slice(1, -1);
    fileEnv[m[1]] = v;
  }
} else {
  console.warn('Warning: no .env file; using environment variables only (see .env.example).');
}

// Process environment variables take precedence (useful in CI)
const get = k => process.env[k] ?? fileEnv[k];
const list = s => (s || '').split(/[\s,]+/).filter(Boolean);

const config = {
  siteName: get('SITE_NAME') || 'tasaK',
  rateName: get('RATE_NAME') || 'Tasa K',
  logo: get('LOGO') || '',
  logoLight: get('LOGO_LIGHT') || '',
  // Default theme (light | dark); empty = the system's
  theme: ['light', 'dark'].includes(get('THEME')) ? get('THEME') : '',
  // Default language (es | en); empty = the browser's
  language: ['es', 'en'].includes(get('LANGUAGE')) ? get('LANGUAGE') : '',
  mostros: list(get('MOSTRO_PUBKEYS')),
  relays: list(get('RELAYS')),
  // Empty: the most traded currency on the node and the visitor's browser time zone
  fiat: (get('FIAT') || '').toUpperCase(),
  timeZone: get('TIMEZONE') || '',
  community: { name: get('COMMUNITY') || '', url: get('COMMUNITY_URL') || '' },
  socialLinks: list(get('SOCIAL_LINKS')),
  // Comma separated only: names may contain spaces («Saldo móvil»)
  hiddenPaymentMethods: get('HIDDEN_PAYMENT_METHODS') == null ? ['Pruebas', 'Otros']
    : get('HIDDEN_PAYMENT_METHODS').split(',').map(s => s.trim()).filter(Boolean),
};

const errors = [];
if (!config.mostros.length) errors.push('MOSTRO_PUBKEYS is empty');
for (const k of config.mostros) {
  if (!/^([0-9a-f]{64}|npub1[02-9ac-hj-np-z]{58})$/i.test(k)) errors.push(`invalid pubkey: ${k}`);
}
if (!config.relays.length) errors.push('RELAYS is empty');
for (const r of config.relays) {
  // Encrypted only (wss://); ws:// just for a local test relay
  if (!/^wss:\/\/\S+$/i.test(r) && !/^ws:\/\/(localhost|127\.0\.0\.1)(:\d+)?(\/\S*)?$/i.test(r)) {
    errors.push(`invalid relay (must start with wss://): ${r}`);
  }
}
for (const u of [config.community.url, ...config.socialLinks].filter(Boolean)) {
  if (!/^https:\/\/\S+$/i.test(u)) errors.push(`invalid link (must start with https://): ${u}`);
}
if (config.timeZone) {
  try { new Intl.DateTimeFormat('en', { timeZone: config.timeZone }); }
  catch { errors.push(`invalid TIMEZONE: ${config.timeZone}`); }
}
for (const [k, v] of [['LOGO', config.logo], ['LOGO_LIGHT', config.logoLight]].filter(([, v]) => v)) {
  if (!/^(https:\/\/\S+|[\w./-]+\.(svg|png|jpe?g|webp))$/i.test(v)) {
    errors.push(`invalid ${k} (.svg/.png/.jpg/.webp file or https link): ${v}`);
  } else if (!v.startsWith('https://') && !existsSync(new URL(v, web))) {
    errors.push(`${k} file not found in web/: ${v}`);
  }
}
if (errors.length) {
  console.error('Configuration error:\n  ' + errors.join('\n  '));
  process.exit(1);
}

writeFileSync(new URL('config.js', web),
  `// Generated by build.mjs from .env. Do not edit by hand.\nwindow.TASAK_CONFIG = ${JSON.stringify(config, null, 2)};\n`);

// The pure logic of the rate (shared/*.js, without its tests), as ES modules for the pages
const sharedSrc = new URL('shared/', root);
const sharedDst = new URL('shared/', web);
rmSync(sharedDst, { recursive: true, force: true });
mkdirSync(sharedDst);
const modules = readdirSync(sharedSrc).filter(f => f.endsWith('.js'));
for (const f of modules) copyFileSync(new URL(f, sharedSrc), new URL(f, sharedDst));

console.log(`web/config.js generated: ${config.mostros.length} node(s), ${config.relays.length} relay(s), `
  + `currency ${config.fiat || 'auto'}; ${modules.length} modules copied to web/shared/`);
// The pages use ES modules, which browsers don't load from file://: they need a web server
console.log('To see it: python3 -m http.server 8765 -d web  ->  http://localhost:8765/');
