// Shared by index.html and node.html: configuration, formatting and node information.

// External images (the node's picture) that fail to load are removed. A listener instead of an inline
// onerror=, which a Content Security Policy blocks; in the capture phase, because errors don't bubble
document.addEventListener('error', e => { if (e.target.matches?.('img[data-hide-broken]')) e.target.remove(); }, true);

// npub (bech32) -> hex, without dependencies.
function toHex(key) {
  const s = String(key).trim().toLowerCase();
  if (/^[0-9a-f]{64}$/.test(s)) return s;
  const CH = 'qpzry9x8gf2tvdw0s3jn54khce6mua7l';
  const m = s.match(/^npub1([02-9ac-hj-np-z]+)$/);
  if (!m) return null;
  let acc = 0, bits = 0, hex = '';
  for (const c of m[1].slice(0, -6)) {   // the last 6 characters are the checksum
    acc = ((acc << 5) | CH.indexOf(c)) & 0xfff;
    bits += 5;
    if (bits >= 8) { bits -= 8; hex += ((acc >> bits) & 0xff).toString(16).padStart(2, '0'); }
  }
  return hex.length === 64 ? hex : null;
}

// Relays: encrypted only (wss://); ws:// just for a local test relay
const validRelay = u => /^wss:\/\/\S+$/i.test(u) || /^ws:\/\/(localhost|127\.0\.0\.1)(:\d+)?(\/\S*)?$/i.test(u);

// Configuration: .env (config.js) with the URL parameters on top
const CONFIG = (() => {
  const base = window.TASAK_CONFIG || {};
  const qs = new URLSearchParams(location.search);
  const list = k => (qs.get(k) || '').split(/[\s,]+/).filter(Boolean);
  const mostros = list('mostro').length ? list('mostro') : base.mostros || [];
  const relays = list('relays').length ? list('relays') : base.relays || [];
  return {
    fromEnv: !!window.TASAK_CONFIG,
    // The community and its links describe the .env nodes; not shown if the URL changes the node
    community: list('mostro').length ? null : base.community,
    socialLinks: list('mostro').length ? [] : (base.socialLinks || []).filter(u => /^https:\/\//i.test(u)),
    mostros: [...new Set(mostros.map(toHex).filter(Boolean))],
    relays: [...new Set(relays.filter(validRelay))],
    siteName: base.siteName || 'tasaK',
    rateName: base.rateName || 'Tasa K',
    logo: base.logo || '',
    logoLight: base.logoLight || '',
    // The tab's icon, a file of the site (svg, png or ico); empty = favicon.svg, generated by tasak
    favicon: /^[\w./-]+\.(svg|png|ico)$/i.test(base.favicon || '') ? base.favicon : '',
    theme: base.theme || '',
    hiddenPaymentMethods: base.hiddenPaymentMethods || ['Pruebas', 'Otros'],
    // Without a configured currency, the page picks the most traded one on the node; the .env one
    // belongs to the .env nodes, so it doesn't apply if the URL changes the node
    fiat: (qs.get('fiat') || (list('mostro').length ? '' : base.fiat) || '').toUpperCase(),
    tz: base.timeZone || Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC',
    // The key that signs the site's Tasa K (hex): its rate is about the .env's nodes, so it doesn't
    // apply if the URL changes the node
    ratePubkey: !list('mostro').length && /^[0-9a-f]{64}$/.test(base.ratePubkey || '') ? base.ratePubkey : '',
  };
})();

// ---------- Light / dark theme ----------
// Choice saved in this browser > THEME in .env > system theme.
// Applied as soon as common.js loads (in <head>) so the page does not flicker.
let THEME = (() => {
  try { const s = localStorage.getItem('tasak.theme'); if (s === 'light' || s === 'dark') return s; } catch {}
  if (CONFIG.theme === 'light' || CONFIG.theme === 'dark') return CONFIG.theme;
  return matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark';
})();
document.documentElement.dataset.theme = THEME;

// Switches the theme without reloading; pages listen to 'themechange' to repaint what is not CSS (chart)
function setTheme(theme) {
  THEME = theme;
  document.documentElement.dataset.theme = theme;
  try { localStorage.setItem('tasak.theme', theme); } catch {}
  applyNames();
  renderThemeButtons();
  document.dispatchEvent(new Event('themechange'));
}
function renderThemeButtons() {
  for (const b of document.querySelectorAll('.theme-btn')) {
    b.textContent = THEME === 'light' ? '☾' : '☀';
    b.title = t(THEME === 'light' ? 'Tema oscuro' : 'Tema claro');
    b.setAttribute('aria-label', b.title);
  }
}
document.addEventListener('DOMContentLoaded', () => {
  renderThemeButtons();
  for (const b of document.querySelectorAll('.theme-btn')) b.onclick = () => setTheme(THEME === 'light' ? 'dark' : 'light');
});

// ---------- Site and rate names (configurable in .env) ----------
// Logo: if the name ends in capitals (tasaK), that part is highlighted
function brandHtml(name = CONFIG.siteName) {
  const m = name.match(/^(.*[^A-Z])([A-Z]+)$/);
  return m ? `${esc(m[1])}<span>${esc(m[2])}</span>` : esc(name);
}
// Fills the texts marked with data-name and the tab title
function applyNames() {
  for (const el of document.querySelectorAll('[data-name="site"]')) {
    // With LOGO in .env the image is shown (LOGO_LIGHT in the light theme); if it fails, the name as text
    const logo = THEME === 'light' && CONFIG.logoLight ? CONFIG.logoLight : CONFIG.logo;
    el.innerHTML = logo
      ? `<img class="brand-logo" src="${esc(logo)}" alt="${esc(CONFIG.siteName)}">`
      : brandHtml();
    el.querySelector('img')?.addEventListener('error', () => { el.innerHTML = brandHtml(); });
  }
  for (const el of document.querySelectorAll('[data-name="rate"]')) el.textContent = CONFIG.rateName;
  document.title = document.title.replace('tasaK', CONFIG.siteName);
  // The icon: FAVICON of .env or, without it, favicon.svg, generated by tasak from SITE_NAME (files of the
  // site: an image data: URI would need the Content Security Policy to allow them)
  const icon = document.querySelector('link[rel="icon"]');
  if (icon && CONFIG.favicon) {
    icon.type = { svg: 'image/svg+xml', png: 'image/png', ico: 'image/x-icon' }[CONFIG.favicon.split('.').pop().toLowerCase()];
    icon.href = CONFIG.favicon;
  }
}
document.addEventListener('DOMContentLoaded', applyNames);

// Opened as a file (file://), browsers don't load ES modules, so the page stays empty: say how to open it
document.addEventListener('DOMContentLoaded', () => {
  if (location.protocol !== 'file:' || !document.querySelector('script[type="module"]')) return;
  const box = document.createElement('div');
  box.className = 'file-warning';
  box.textContent = t('Esta página no funciona abierta como archivo. Sírvela con un servidor web: en la carpeta del repositorio ejecuta «{cmd}» y abre {url}',
    { cmd: 'tasak', url: 'http://localhost:8765/' });
  document.body.prepend(box);
});

const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const fmtInt = n => Math.round(n).toLocaleString(LOCALE);
const fmtTime = ts => new Date(ts * 1000).toLocaleString(LOCALE, {
  timeZone: CONFIG.tz, day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23',
});

// ---------- Node information: profile (0), information (38385) and relays (10002) ----------
const META_KINDS = [0, 38385, 10002];

// Keeps in `metaMap` (pubkey -> { profile, info, relays }) the newest version of each event
function applyMeta(metaMap, ev) {
  const m = metaMap.get(ev.pubkey) || {};
  const slot = { 0: 'profile', 38385: 'info', 10002: 'relays' }[ev.kind];
  if (!slot || (m[slot] && m[slot].ts >= ev.created_at)) return false;
  if (ev.kind === 0) {
    let p;
    try { p = JSON.parse(ev.content); } catch { return false; }
    m.profile = { ts: ev.created_at, ...p };
  } else if (ev.kind === 38385) {
    const t = {};
    for (const [k, v] of ev.tags) if (!(k in t)) t[k] = v;
    m.info = { ts: ev.created_at, ...t };
  } else {
    m.relays = { ts: ev.created_at, list: ev.tags.filter(t => t[0] === 'r').map(t => t[1]) };
  }
  metaMap.set(ev.pubkey, m);
  return true;
}

// Readable name of a social network from its link
function linkLabel(u) {
  try {
    const url = new URL(u);
    const h = url.hostname.replace(/^www\./, '');
    const path = url.pathname.replace(/\/$/, '').split('/').pop();
    if (h === 't.me') return `Telegram · @${path}`;
    if (h === 'x.com' || h === 'twitter.com') return `X · @${path}`;
    if (h === 'youtube.com') return `YouTube · ${decodeURIComponent(path)}`;
    if (h === 'github.com') return `GitHub · ${path}`;
    if (/primal\.net|njump\.me|nostr/.test(h)) return t('Nostr de la comunidad');
    return h;
  } catch { return u; }
}
const extLink = (u, label) => /^https:\/\//i.test(u) ? `<a href="${esc(u)}" target="_blank" rel="noopener">${esc(label)} ↗</a>` : '';

// HTML card of a node. `activity` are rows [label, HTML value] with data from its orders.
function nodeCardHtml(pk, m = {}, activity = []) {
  const fmtSats = n => `${fmtInt(Number(n))} sats`;
  const fmtDur = sec => sec >= 3600 ? `${sec / 3600} h` : `${Math.round(sec / 60)} min`;
  const p = m.profile || {}, info = m.info;
  const npub = window.NostrTools?.nip19?.npubEncode(pk) || pk;
  // Its orders (38383) and information (38385), as the relays return them
  const nodeEventsUrl = 'https://nostrinspect.com/?relays=' + encodeURIComponent(CONFIG.relays.map(r => r.replace(/^wss:\/\//i, '')).join(',')).replace(/%2C/g, ',')
    + '&authors=' + npub + '&kinds=38383,38385&limit=100';
  const kv = rows => `<dl class="node-kv">${rows.filter(Boolean).map(([k, v]) => `<dt>${k}</dt><dd>${v}</dd>`).join('')}</dl>`;

  const links = [
    p.website && extLink(p.website, t('Web del nodo')),
    CONFIG.community?.url && extLink(CONFIG.community.url, CONFIG.community.name || t('Comunidad')),
    ...CONFIG.socialLinks.map(u => extLink(u, linkLabel(u))),
    extLink(nodeEventsUrl, t('Eventos del nodo en Nostr')),
  ].filter(Boolean).join('');

  return `<div class="node-card">
    <div class="node-top">
      ${p.picture && /^https:\/\//.test(p.picture) ? `<img alt="" src="${esc(p.picture)}" data-hide-broken>` : ''}
      <div>
        <h3>${esc(p.name || pk.slice(0, 8) + '…')}</h3>
        ${p.about ? `<p>${esc(p.about)}</p>` : ''}
        ${CONFIG.community?.name ? `<p>${t('Comunidad:')} <strong>${esc(CONFIG.community.name)}</strong></p>` : ''}
      </div>
    </div>
    ${links ? `<div class="node-links">${links}</div>` : ''}

    <div class="node-sec">${t('Condiciones')}</div>
    ${info ? kv([
      info.fee != null && [t('Comisión del nodo'), t('{p} del monto de cada orden', { p: `<strong>${(Number(info.fee) * 100).toLocaleString(LOCALE, { maximumFractionDigits: 2 })}${LANG === 'en' ? '' : ' '}%</strong>` })],
      info.min_order_amount && [t('Monto por orden'), `${fmtSats(info.min_order_amount)} – ${fmtSats(info.max_order_amount)}`],
      info.expiration_hours && [t('Una orden publicada dura'), `${esc(info.expiration_hours)} h`],
      info.expiration_seconds && [t('Tiempo para seguir una orden tomada'), fmtDur(Number(info.expiration_seconds))],
      [t('Estado'), info.maintenance_mode === 'true' ? `<span class="accent">${t('⚠ en mantenimiento')}</span>` : `<span class="up">${t('● operativo')}</span>`],
    ]) : `<p class="muted">${t('El nodo aún no ha enviado su información (evento kind 38385).')}</p>`}

    ${activity.length ? `<div class="node-sec">${t('Actividad')}</div>${kv(activity)}` : ''}

    <div class="node-sec">${t('Técnico')}</div>
    ${kv([
      [t('Clave pública'), `<span class="num">${esc(npub)}</span>`],
      info?.mostro_version && ['Mostro', `v${esc(info.mostro_version)}${info.protocol_version ? ` · ${t('protocolo {v}', { v: esc(info.protocol_version) })}` : ''}`],
      info?.lnd_node_alias && [t('Nodo Lightning'), `${esc(info.lnd_node_alias)}${info.lnd_version ? ` · LND ${esc(info.lnd_version.split(' ')[0])}` : ''}`],
      info?.lnd_node_pubkey && [t('Clave pública del nodo Lightning'), `<span class="num">${esc(info.lnd_node_pubkey)}</span>`],
      m.relays?.list.length && [t('Relays del nodo'), m.relays.list.map(esc).join('<br>')],
      info && [t('Información publicada'), esc(fmtTime(info.ts))],
    ])}
  </div>`;
}
